amp_opt_level: 1
assume_yes: false
base_lr: 0.01
batch_size: 32
checkpoint: null
config: ./config/smplx49-cross-subject/test_joint.yaml
debug: false
device:
- 0
- 1
- 2
- 3
eval_interval: 1
eval_start: 1
feeder: feeders.feeder.Feeder
forward_batch_size: 16
half: false
ignore_weights: []
log_interval: 100
model: model.msg3d.Model
model_args:
  graph: graph.ntu_rgb_d.AdjMatrixGraph
  num_class: 49
  num_g3d_scales: 6
  num_gcn_scales: 13
  num_person: 1
  num_point: 67
model_saved_name: ''
nesterov: false
num_epoch: 80
num_worker: 40
optimizer: SGD
optimizer_states: null
phase: test
print_log: true
save_interval: 1
save_score: true
seed: 98
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 40
- 60
test_batch_size: 100
test_feeder_args:
  data_path: ./data/smplx_49_frontal_1_person/test_joint_data.npy
  debug: false
  label_path: ./data/smplx_49_frontal_1_person/test_labels.npy
train_feeder_args: {}
weight_decay: 0.0005
weights: ./work_dir/smplx49/xsub_67/joint/weights/weights-40-16452.pt
work_dir: ./eval/smplx49/xsub_67/joint
