
work_dir: ./work_dir/ntu120/xsub/msg3d_joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/smplx_49_frontal_1_person/train_joint_data.npy
  label_path: ./data/smplx_49_frontal_1_person/train_labels.npy
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/smplx_49_frontal_1_person/test_joint_data.npy
  label_path: ./data/smplx_49_frontal_1_person/test_labels.npy

# model
model: model.msg3d.Model
model_args:
  num_class: 49
  num_point: 67
  num_person: 1
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [30, 50]

# training
num_epoch: 60
device: [0,1, 2, 3]
batch_size: 32
forward_batch_size: 16
test_batch_size: 120
nesterov: True
